# Generated by Django 3.2.7 on 2021-12-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211206_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='lingitude',
            new_name='longitude',
        ),
    ]
