# Generated by Django 3.2.7 on 2021-12-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_lingitude_city_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
