# Generated by Django 3.2.7 on 2021-12-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('date_cr',)},
        ),
    ]
