# Generated by Django 3.2.7 on 2021-12-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),
    ]
